library(readxl)
library(CausalImpact)
Risk_Sector <- read_csv("Risk_Sector.csv")
df<-Risk_Sector
head(df)
matplot(df, type = "l", ylab = "Risk Score", xlab = "number of obs", main = "Sector risk time series")
pre.period <- c(1, 170)
post.period <- c(171, 208)
impact <- CausalImpact(df, pre.period, post.period)
plot(impact)
summary(impact)
